class Locators():

    # login
    login_altera_metodo = 'login__arrow-buttons-wrapper'
    login_altera_para_pin = '// *[ @ id = "login-button-pin"]'
    login_altera_para_pin_id = 'login-button-pin'
    login_seleciona_linguagem = '//*[@id="ndd-ng-language-selector"]'
    login_seleciona_linguagem_id = 'ndd-ng-language-selector'
    login_select_es_es = '//*[@id="ndd-ng-option-Español"]'
    login_select_es_es_id = 'id="ndd-ng-option-Español'
    login_select_pt_br = '//*[@id="ndd-ng-option-Português"]'
    login_select_pt_br_id = 'ndd-ng-option-Português'
    login_select_en_us = '//*[@id="ndd-ng-option-English"]'
    login_select_en_us_id = 'ndd-ng-option-English'
    login_botao_submit_id = 'login-button-submit'
    input_pin_id = 'login-input-pin'
    input_password_id = 'login-input-password'
    input_username_id = 'login-input-username'
    message_login_fail = '/html/body/ndd-app/div/ng-component/div/div[1]/div/div[2]/ndd-ng-spinner/fieldset/ng-component/div/ndd-ng-spinner/fieldset/form/div[2]/span'
    message_login_fail_id = 'login-form-validation-message'

    # geral
    msg_host_incompativel_id = 'div-error-message-host-version'
    spinner_loading = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/div'
    upload_dropdown_second_item = '//*[@id="documents-pending-list-grid-header-actionbar-dropdown-options"]/div/ndd-ng-dropdown-option[2]'
    upload_botao_up_sem_dropdown = '//*[@id="documents-action-upload"]'
    upload_area_clicavel_para_selecionar_arquivo = '/html/body/ndd-app/ng-component/ndd-ng-off-side-screen/div/div[2]/ndd-ng-spinner/fieldset/div[1]/div/div/form/ndd-ng-upload/div/kendo-upload'
    upload_botao_up_final_id = 'offside-screen-button-add'
    docs_rodape_numero_docs_info = '/html/body/ndd-app/div/ndd-layout/div/ng-component/ndd-ng-spinner/fieldset/div/ndd-documents/div/ndd-ng-grid/section/div[2]/div/kendo-grid/kendo-pager/kendo-pager-info'
    docs_seleciona_primeiro_item = '//*[@id="k-grid0-checkbox0"]'
    docs_seleciona_primeiro_item_id = 'k-grid0-checkbox0'
    docs_botao_select_all = '/html/body/ndd-app/div/ndd-layout/div/ng-component/ndd-ng-spinner/fieldset/div/ndd-documents/div/ndd-ng-grid/section/div[2]/div/kendo-grid/div/div/div/table/thead/tr/th[1]/input'
    docs_imprimir_sem_dropdown = '// *[ @ id = "documents-action-print"]'
    docs_imprimir_sem_dropdown_id = 'documents-action-print'
    docs_excluir_sem_dropdown = '//*[@id="documents-action-delete"]'
    docs_excluir_sem_dropdown_id = 'documents-action-delete'
    docs_drop_down = '// *[@ id = "documents-pending-list-grid-header-actionbar-dropdown-btn"]'
    docs_drop_down_id = 'documents-pending-list-grid-header-actionbar-dropdown-btn'
    docs_drop_down_first_item_IMPRIMIR = '//*[@id="documents-pending-list-grid-header-actionbar-dropdown-options"]/div/ndd-ng-dropdown-option[1]'
    docs_clica_primeiro_item = '/html/body/ndd-app/div/ndd-layout/div/ng-component/ndd-ng-spinner/fieldset/div/ndd-documents/div/ndd-ng-grid/section/div[2]/div/kendo-grid/div/kendo-grid-list/div/div[1]/table/tbody/tr/td[2]/a'
    botao_ok_apos_imprimir = '//*[@id="ndd-ng-dialog-button-ok"]'
    botao_ok_apos_imprimir_id = 'ndd-ng-dialog-button-ok'
    botao_imprimir_final = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[2]/ndd-ng-|1button[1]'
    botao_selecionar_impressora_final_id = 'offside-screen-button-add'
    botao_user_css = '.layout__navbar__menu__data__fullname'
    botao_sair_css = '.layout__offsidebar__footer__logout-btn'
    usuario_logado = '/html/body/ndd-app/div/ndd-layout/ndd-ng-offsidebar[1]/div/div/div[1]/div/ndd-layout-user-menu-header/div/div/div[2]/div[2]/span'
    usuario_logado_email = '/html/body/ndd-app/div/ndd-layout/ndd-ng-offsidebar[1]/div/div/div[1]/div/ndd-layout-user-menu-header/div/div/div[2]/div[3]/span'
    mensagem_rodape_lista_jobs = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/ndd-documents-print-view-printing-summary/div/ndd-documents-print-view-printing-summary-message/div/span'
    string_sem_saldo_ptBR = 'Documentos selecionados excedem seu saldo'
    msg_print_success_id = 'print-sucess-message'
    msg_auth_nao_configurada = 'div-error-message-no-authentication-defined'

    # dashboard
    moeda_saldo_corporate = 'money-corporate-quota-value'
    moeda_saldo_private = 'money-private-quota-value'
    paginas_saldo_corporate = 'pages-corporate-quota-value'
    paginas_saldo_private = 'pages-private-quota-value'
    cor_saldo_corporate_mono = 'pages-mono-corporate-quota-value'
    cor_saldo_corporate_color = 'pages-color-corporate-quota-value'
    cor_saldo_private_mono = 'pages-mono-private-quota-value'
    cor_saldo_private_color = 'pages-color-private-quota-value'
    total_docs_printed = 'total-documents-value'
    total_pages_printed = 'total-pages-value'
    espaco_em_disco_utilizado = '//*[@id="storage-quota-stored-value"]'
    espaco_em_disco_utilizado_id = 'storage-quota-stored-value'
    espaco_em_disco_utilizado_unidade = '//*[@id="storage-quota-stored-unit"]'
    espaco_em_disco_utilizado_unidade_id = 'storage-quota-stored-unit'
    espaco_em_disco_disponivel = '//*[@id="storage-quota-total-value"]'
    espaco_em_disco_disponivel_id = 'storage-quota-total-value'
    espaco_em_disco_disponivel_unidade = '//*[@id="storage-quota-total-unit"]'
    espaco_em_disco_disponivel_unidade_id = 'storage-quota-total-unit'

    # meus docs
    botao_meusDocs = '// *[ @ id = "menu-pending"]'
    botao_meusDocs_id = 'menu-pending'

    # docs salvos
    botao_meusSalvos = '// *[ @ id = "menu-saved"]'
    salvos_meusSalvos_id = 'menu-saved'


    # propriedade dos docs
    doc_prop_botao_editar = '//*[@id="ndd-ng-button-action"]'
    doc_prop_botao_editar_id = 'ndd-ng-button-action'
    doc_prop_seleciona_particular = '/html/body/ndd-app/div/ndd-layout/div/ng-component/div/ng-component/section/ndd-ng-spinner/fieldset/form/div[1]/ndd-jobs-assignment/form/ndd-ng-form-fieldset/fieldset/div/ndd-ng-form-fieldset/fieldset/div/ndd-ng-radio-button-group/div/ndd-ng-radio-button[1]/div[1]/fieldset/label'
    doc_prop_salvar = '//*[@id="documents-edit-save-button"]'
    doc_prop_salvar_id = 'documents-edit-save-button'
    doc_prop_data_hora_envio_id = 'documentinfodetail-dataitem-datetimeprint'
    doc_prop_finalidade_pre_selecionada_id = 'documentinfodetail-dataitem-finality'
    doc_prop_finalidade_conta_pre_selecionada_id = 'documentinfodetail-dataitem-accountattribution'
    doc_prop_primeira_conta = '/html/body/ndd-app/div/ndd-layout/div/ng-component/div/ng-component/section/ndd-ng-spinner/fieldset/form/div[1]/ndd-jobs-assignment/form/div/ndd-ng-grid/section/div[2]/div/kendo-grid/div/kendo-grid-list/div/div[1]/table/tbody/tr[1]/td[1]/span'
    doc_prop_duplex_simplex_id = 'documentinfodetail-dataitem-isduplex'
    doc_prop_tamanho_papel_id = 'documentinfodetail-dataitem-papersize'
    doc_prop_paginas_id = 'documentinfodetail-dataitem-pages'
    doc_prop_tamanho_job_id = 'documentinfodetail-dataitem-documentsize'
    doc_prop_tipo_id = 'documentinfodetail-dataitem-type'
    doc_prop_botao_fechar = '//*[@id="ndd-ng-titlebar-btn-close"]'
    doc_prop_botao_fechar_id = 'ndd-ng-titlebar-btn-close'

    # pagina impressao
    reprografia_color = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[1]/div[1]/ndd-ng-form-fieldset[1]/fieldset/div/ndd-ng-radio-button-group[1]/div/ndd-ng-radio-button[2]/div[1]'
    reprografia_mono = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[1]/div[1]/ndd-ng-form-fieldset[1]/fieldset/div/ndd-ng-radio-button-group[1]/div/ndd-ng-radio-button[1]/div[1]'
    reprografia_simplex = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[1]/div[1]/ndd-ng-form-fieldset[1]/fieldset/div/ndd-ng-radio-button-group[2]/div/ndd-ng-radio-button[2]/div[1]'
    reprografia_duplex = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[1]/div[1]/ndd-ng-form-fieldset[1]/fieldset/div/ndd-ng-radio-button-group[2]/div/ndd-ng-radio-button[1]/div[1]'
    botao_exibir_detalhes = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/ndd-documents-print-view-printing-summary/div/ndd-documents-print-view-printing-summary-message/div/a'
    pg_print_botao_imprimir_final = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[2]/ndd-ng-button[1]'
    pg_print_botao_sel_imp = '//*[@id="select-printer-button"]'
    pg_print_botao_sel_imp_id = 'select-printer-button'
    pg_print_seleciona_segunda_imp = '/html/body/ndd-app/ng-component/ndd-ng-off-side-screen/div/div[2]/ndd-ng-spinner/fieldset/div[1]/div/div/ndd-ng-grid/section/div[2]/div/kendo-grid/div/kendo-grid-list/div/div[1]/table/tbody/tr[2]/td[1]'
    pg_print_botao_selec_imp_final = '//*[@id="docprint-btn-print"]'
    pg_print_botao_selec_imp_final_id = 'docprint-btn-print'
    pg_print_botao_selec_imp_e_salvar_final = '//*[@id="docprint-btn-print-and-save"]'
    pg_print_botao_selec_imp_e_salvar_final_id = 'docprint-btn-print-and-save'
    pg_print_imp_selecionada = '//*[@id="select-printer-input"]'
    pg_print_imp_selecionada_id = 'select-printer-input'
    pg_print_botao_simplex = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[1]/div[1]/ndd-ng-form-fieldset[1]/fieldset/div/ndd-ng-radio-button-group[2]/div/ndd-ng-radio-button[2]/div[1]/fieldset/label'
    pg_print_botao_duplex = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[1]/div[1]/ndd-ng-form-fieldset[1]/fieldset/div/ndd-ng-radio-button-group[2]/div/ndd-ng-radio-button[1]/div[1]/fieldset/label'
    pg_print_botao_color = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[1]/div[1]/ndd-ng-form-fieldset[1]/fieldset/div/ndd-ng-radio-button-group[1]/div/ndd-ng-radio-button[2]/div[1]/fieldset/label'
    pg_print_botao_mono = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[1]/div[1]/ndd-ng-form-fieldset[1]/fieldset/div/ndd-ng-radio-button-group[1]/div/ndd-ng-radio-button[1]/div[1]/fieldset/label'
    pg_print_lista_jobs_Conta = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr[1]/td[7]/span'
    pg_print_lista_jobs_Finalidade = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr/td[6]/span'
    pg_print_lista_jobs_Custo = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr/td[5]/span'
    pg_print_lista_jobs_pgColor = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr/td[4]/span'
    pg_print_lista_jobs_pgMono = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr/td[3]/span'
    pg_print_lista_jobs_Data = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr/td[2]/span'
    pg_print_lista_jobs_Nome = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr/td[1]/span'
    pg_print_lista_botao_Editar = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr/td[7]/button[1]'
    pg_print_lista_botao_Editar_todos = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr/td[7]/button[1]'
    pg_print_lista_botao_Excluir = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr/td[7]/button[2]'
    pg_print_lista_edit_botao_Particular = '/html/body/ndd-app/ng-component/ndd-ng-off-side-screen/div/div[2]/ndd-ng-spinner/fieldset/div[1]/div/div/form/div/ndd-jobs-assignment/form/ndd-ng-form-fieldset/fieldset/div/ndd-ng-form-fieldset/fieldset/div/ndd-ng-radio-button-group/div/ndd-ng-radio-button[1]/div[1]'
    pg_print_lista_edit_botao_Corporativo = '/html/body/ndd-app/ng-component/ndd-ng-off-side-screen/div/div[2]/ndd-ng-spinner/fieldset/div[1]/div/div/form/div/ndd-jobs-assignment/form/ndd-ng-form-fieldset/fieldset/div/ndd-ng-form-fieldset/fieldset/div/ndd-ng-radio-button-group/div/ndd-ng-radio-button[2]/div[1]'
    pg_print_lista_edit_botao_Atribuir = '/html/body/ndd-app/ng-component/ndd-ng-off-side-screen/div/div[2]/ndd-ng-spinner/fieldset/div[2]/div/div/ndd-ng-button[1]'
    pg_print_mensagem_jobs_sem_conta = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/ndd-documents-print-view-printing-summary/div/ndd-documents-print-view-printing-summary-message/div/span'
    pg_print_botão_Voltar = '//*[@id="docprint-btn-back"]'
    pg_print_botão_Voltar_id = 'docprint-btn-back'
    pg_print_botao_Confirmar_sair_alteracoes = '//*[@id="ndd-ng-dialog-button-ok"]'
    pg_print_botao_Confirmar_sair_alteracoes_id = 'ndd-ng-dialog-button-ok'
    pg_print_botao_Cancelar_sair_alteracoes = '//*[@id="ndd-ng-dialog-button-cancel"]'
    pg_print_botao_Cancelar_sair_alteracoes_id = 'ndd-ng-dialog-button-cancel'
    pg_print_botao_diminuir_copias = '//*[@id="print-copy-number-btn-decrease"]'
    pg_print_botao_diminuir_copias_id = 'print-copy-number-btn-decrease'
    pg_print_botao_aumentar_copias = '//*[@id="print-copy-number-btn-increase"]'
    pg_print_botao_aumentar_copias_id = 'print-copy-number-btn-increase'
    pg_print_ordenacao_nome = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/thead/tr/th[1]/span[1]/span'
    pg_print_ordenacao_data = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/thead/tr/th[2]/span[1]/span'
    pg_print_ordenacao_pgMono = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/thead/tr/th[3]/span[1]/span'
    pg_print_ordenacao_pgColor = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/thead/tr/th[4]/span[1]/span'
    pg_print_ordenacao_custo = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/thead/tr/th[5]/span[1]/span'
    pg_print_ordenacao_finalidade = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/thead/tr/th[6]/span[1]/span'
    pg_print_custo_corporativo = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/ndd-documents-print-view-printing-summary/div/ndd-ng-data/dl/div/ndd-ng-data-item[1]/dd/span'
    pg_print_custo_particular = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/ndd-documents-print-view-printing-summary/div/ndd-ng-data/dl/div/ndd-ng-data-item[2]/dd/span'
    pg_print_total_pg_mono_corp = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/ndd-documents-print-view-printing-summary/div/ndd-ng-data/dl/div/ndd-ng-data-item[1]/dd/span'
    pg_print_total_pg_mono_part = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/ndd-documents-print-view-printing-summary/div/ndd-ng-data/dl/div/ndd-ng-data-item[2]/dd/span'
    pg_print_total_pg_color_corp = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/ndd-documents-print-view-printing-summary/div/ndd-ng-data/dl/div/ndd-ng-data-item[3]/dd/span'
    pg_print_total_pg_color_part = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/ndd-documents-print-view-printing-summary/div/ndd-ng-data/dl/div/ndd-ng-data-item[4]/dd/span'
    pg_print_custo_total = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/ndd-documents-print-view-printing-summary/div/ndd-ng-data/dl/div/ndd-ng-data-item[5]/dd/span'

    # politicas e conversões
    politicas_bloqueado = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr/td[1]/span[2]/i'
    politicas_liberado = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr[2]/td[1]/span[1]/i'
    politicas_lista_qtde_a_imprmir = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[2]/span'
    politicas_lista_qtde_a_imprimir2 = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-spinner/fieldset/form/div[2]/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[2]/span'
    conversao_mono_checked = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr[1]/td[7]/ndd-ng-light-grid-column-wrapper/ng-component/span/form/ndd-ng-checkbox/div/fieldset/label/div'
    conversao_duplex_checked = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr[1]/td[8]/ndd-ng-light-grid-column-wrapper/ng-component/span/form/ndd-ng-checkbox/div/fieldset/label/div'
    conversao_status = '/html/body/ndd-app/div/ndd-layout/div/ng-component/section/ndd-ng-spinner/fieldset/div[1]/ng-component/ndd-ng-form-fieldset/fieldset/div/ndd-ng-light-grid/div/div[1]/table/tbody/tr[%s]/td[1]/span[2]/i'
